/**
 * Everything the valuation-revisions screen decides, as pure functions.
 *
 * The screen itself only renders: which Books state a row is in, whether a delta is cost
 * pressure or relief, what the insight panel is allowed to claim and which of those claims
 * has a real route behind it all live here, where they can be unit tested. A rule that lives
 * in JSX is a rule nobody can check.
 */

import type {
  RevisionItemSplit,
  RevisionSummary,
  RevisionTriggerSplit,
  ValuationRevision,
} from '../../../services/valuationApi'
import { formatDate, humanize } from '../../../utils/format'

export type Tone = 'neutral' | 'primary' | 'success' | 'warning' | 'danger' | 'info'

// ---------------------------------------------------------------------------
// Books lifecycle
// ---------------------------------------------------------------------------

/**
 * Where a revision has got to between the two products.
 *
 * Inventory generates it (`pending`), publishes it to Books (`published`), and Books
 * acknowledges it once the COGS has been re-posted (`applied`). Three states, not two: only
 * the middle one means "Books has it and has not answered yet", and a screen that merged it
 * with the first would hide a revision that never left Inventory at all — which is the one
 * an operator most needs to find.
 */
export type BooksState = 'pending' | 'published' | 'applied'

export function booksState(r: Pick<ValuationRevision, 'acknowledged' | 'published_at'>): BooksState {
  if (r.acknowledged) return 'applied'
  return r.published_at ? 'published' : 'pending'
}

/**
 * The words the printed sheet and the CSV use.
 *
 * Unchanged since this screen's first version: a file somebody archived last quarter and a
 * file exported today have to say the same thing about the same revision.
 */
export const BOOKS_STATE_SHEET_LABEL: Record<BooksState, string> = {
  pending: 'Pending',
  published: 'Published to Books',
  applied: 'Applied in Books',
}

/** The badge in the table: a short word, with the full state as its title. */
export const BOOKS_STATE_BADGE: Record<BooksState, { label: string; tone: Tone; title: string }> = {
  pending: {
    label: 'Pending',
    tone: 'warning',
    title: 'Generated by a recalculation — not yet published to Books',
  },
  published: {
    label: 'Published',
    tone: 'info',
    title: 'Published to Books — waiting for Books to re-post the COGS',
  },
  applied: {
    label: 'Applied',
    tone: 'success',
    title: 'Applied in Books — the COGS has been re-posted and acknowledged',
  },
}

export const BOOKS_FILTER_OPTIONS = [
  { value: 'unacknowledged', label: 'Awaiting Books' },
  { value: 'pending', label: '— not yet published' },
  { value: 'published', label: '— published, no answer' },
  { value: 'acknowledged', label: 'Applied in Books' },
  { value: 'all', label: 'All revisions' },
] as const

/** Matches the list's own default: work to do first. */
export const DEFAULT_BOOKS_FILTER = 'unacknowledged'

/**
 * The `books` filter as the API's two parameters.
 *
 * `acknowledged` is sent alongside `books` on purpose. It is the parameter this endpoint has
 * always had, so an API deployed before this screen was rebuilt still narrows the list to the
 * right side of the acknowledgement line instead of silently ignoring the filter and showing
 * applied revisions under a heading that says "Awaiting Books".
 */
export function booksFilterQuery(books: string): { books?: string; acknowledged?: string } {
  switch (books) {
    case 'unacknowledged':
      return { books: 'unacknowledged', acknowledged: '0' }
    case 'pending':
      return { books: 'awaiting', acknowledged: '0' }
    case 'published':
      return { books: 'published', acknowledged: '0' }
    case 'acknowledged':
      return { books: 'acknowledged', acknowledged: '1' }
    default:
      // 'all' — and anything unrecognised, which must never narrow silently.
      return {}
  }
}

// ---------------------------------------------------------------------------
// Valuation delta
// ---------------------------------------------------------------------------

export type DeltaDirection = 'increase' | 'decrease' | 'flat'

export function deltaDirection(delta: number | null | undefined): DeltaDirection {
  const n = typeof delta === 'number' && Number.isFinite(delta) ? delta : 0
  if (n > 0) return 'increase'
  if (n < 0) return 'decrease'
  return 'flat'
}

/**
 * What the sign of a valuation delta means, and how it is said out loud.
 *
 * A positive delta is stock that now costs MORE than the books thought it did: margin
 * pressure and a COGS increase to re-post. It is drawn in the warning colour for that reason,
 * not because "negative is red" — on a costing screen that instinct is backwards.
 *
 * `srLabel` exists because the colour is a hint, never the message: it is read out with the
 * figure, so the meaning survives a monochrome print, a colour-blind reader and a screen
 * reader alike.
 */
export const DELTA_MEANING: Record<DeltaDirection, { tone: Tone; srLabel: string }> = {
  increase: { tone: 'danger', srLabel: 'cost increase' },
  decrease: { tone: 'success', srLabel: 'cost decrease' },
  flat: { tone: 'neutral', srLabel: 'no change' },
}

export const DELTA_FILTER_OPTIONS = [
  { value: '', label: 'Any movement' },
  { value: 'increase', label: 'Cost increased' },
  { value: 'decrease', label: 'Cost decreased' },
  { value: 'none', label: 'No change' },
] as const

// ---------------------------------------------------------------------------
// Filters
// ---------------------------------------------------------------------------

export const REVISION_FILTER_KEYS = [
  'books',
  'acknowledged',
  'item_id',
  'warehouse_id',
  'job_id',
  'document_id',
  'document_type',
  'delta',
  'min_abs_delta',
  'from',
  'to',
] as const

/**
 * What "high impact" means, in base currency.
 *
 * A fixed, stated figure rather than a percentile of whatever happens to be on screen: a chip
 * whose meaning moves with the data cannot be compared between two days, and the operator can
 * type any other threshold into the field beside it.
 */
export const HIGH_IMPACT_THRESHOLD = 10000

export interface QuickFilter {
  key: string
  label: string
  title: string
  patch: Record<string, string>
}

/** Monday of the week `now` falls in, ISO. */
export function weekStart(now: Date): string {
  const d = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const shift = (d.getDay() + 6) % 7
  d.setDate(d.getDate() - shift)
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`
}

export function isoDate(now: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`
}

export function quickFilters(now: Date = new Date()): QuickFilter[] {
  return [
    {
      key: 'high-impact',
      label: 'High impact',
      title: `Valuation delta of ${HIGH_IMPACT_THRESHOLD.toLocaleString('en-IN')} or more, either way`,
      patch: { min_abs_delta: String(HIGH_IMPACT_THRESHOLD) },
    },
    {
      key: 'awaiting',
      label: 'Awaiting Books',
      title: 'Everything Books has not acknowledged yet',
      patch: { books: 'unacknowledged' },
    },
    {
      key: 'increase',
      label: 'Cost increases',
      title: 'Revisions that raised the cost of stock',
      patch: { delta: 'increase' },
    },
    {
      key: 'decrease',
      label: 'Cost decreases',
      title: 'Revisions that lowered the cost of stock',
      patch: { delta: 'decrease' },
    },
    {
      key: 'this-week',
      label: 'This week',
      title: 'Revisions created since Monday',
      patch: { from: weekStart(now), to: isoDate(now) },
    },
  ]
}

/** A quick filter is active when every value it sets is already set. */
export function isQuickFilterActive(filter: QuickFilter, filters: Record<string, string>): boolean {
  return Object.entries(filter.patch).every(([k, v]) => (filters[k] ?? '') === v)
}

/** Clearing a chip returns its keys to empty rather than dropping every filter. */
export function clearPatch(filter: QuickFilter): Record<string, string> {
  return Object.fromEntries(Object.keys(filter.patch).map((k) => [k, '']))
}

/**
 * Filters the reader has actually set, as the sheet's meta lines.
 *
 * The Books state is always printed, even at its default: a sheet that silently omitted
 * "awaiting Books" would read as the whole year's revisions.
 */
export function filterSummaryLines(
  filters: Record<string, string>,
  q: string,
  labels: { warehouse?: string; documentType?: string; item?: string },
): string[] {
  const books = filters.books || DEFAULT_BOOKS_FILTER
  const booksLabel = BOOKS_FILTER_OPTIONS.find((o) => o.value === books)?.label ?? 'All revisions'
  const lines = [`Books: ${booksLabel.replace(/^— /, '')}`]
  if (q) lines.push(`Search: ${q}`)
  if (labels.item) lines.push(`Item: ${labels.item}`)
  if (labels.warehouse) lines.push(`Warehouse: ${labels.warehouse}`)
  if (labels.documentType) lines.push(`Source document: ${labels.documentType}`)
  if (filters.job_id) lines.push(`Recalculation job: #${filters.job_id}`)
  if (filters.document_id) lines.push(`Document id: ${filters.document_id}`)
  if (filters.delta) {
    lines.push(`Movement: ${DELTA_FILTER_OPTIONS.find((o) => o.value === filters.delta)?.label ?? filters.delta}`)
  }
  if (filters.min_abs_delta) lines.push(`Minimum absolute delta: ${filters.min_abs_delta}`)
  if (filters.from || filters.to) {
    lines.push(`Created between: ${filters.from ? formatDate(filters.from) : '…'} and ${filters.to ? formatDate(filters.to) : '…'}`)
  }
  return lines
}

// ---------------------------------------------------------------------------
// Selection and acknowledgement
// ---------------------------------------------------------------------------

export interface AckSelection {
  eligible: ValuationRevision[]
  /** Already applied in Books — the API would ignore them, so neither do we. */
  ineligible: ValuationRevision[]
  netDelta: number
  absDelta: number
  /** Eligible rows Books has not been handed yet. Acknowledging these is a claim. */
  awaitingPublish: number
}

export function ackSelection(
  rows: readonly ValuationRevision[],
  selected: ReadonlySet<number>,
): AckSelection {
  const eligible: ValuationRevision[] = []
  const ineligible: ValuationRevision[] = []
  let netDelta = 0
  let absDelta = 0
  let awaitingPublish = 0
  for (const row of rows) {
    if (!selected.has(row.revision_id)) continue
    if (row.acknowledged) {
      ineligible.push(row)
      continue
    }
    eligible.push(row)
    const delta = row.delta_amount ?? 0
    netDelta += delta
    absDelta += Math.abs(delta)
    if (!row.published_at) awaitingPublish += 1
  }
  return { eligible, ineligible, netDelta, absDelta, awaitingPublish }
}

// ---------------------------------------------------------------------------
// Charts
// ---------------------------------------------------------------------------

export const TIMELINE_PERIODS = [
  { value: '10', label: 'Last 10 days' },
  { value: '30', label: 'Last 30 days' },
  { value: '90', label: 'Last 90 days' },
] as const

export interface TimelineColumns {
  categories: string[]
  increased: number[]
  decreased: number[]
  /** True when the window has no revisions at all. */
  empty: boolean
  /** True when the window was longer than the chart will draw, and says so. */
  truncated: boolean
}

/**
 * The timeline, with the quiet days put back.
 *
 * The API only returns days that have revisions, and a bar chart drawn straight from that
 * would space five scattered days evenly and read as five consecutive ones. The window is
 * filled in here so a gap in the data is a gap on the axis.
 */
export function timelineColumns(summary: RevisionSummary | null, maxDays = 90): TimelineColumns {
  const nothing = { categories: [], increased: [], decreased: [], empty: true, truncated: false }
  if (!summary) return nothing
  const byDay = new Map(summary.timeline.map((p) => [p.day, p]))
  const start = new Date(`${summary.window.from}T00:00:00`)
  const end = new Date(`${summary.window.to}T00:00:00`)
  if (Number.isNaN(start.getTime()) || Number.isNaN(end.getTime())) return nothing
  const categories: string[] = []
  const increased: number[] = []
  const decreased: number[] = []
  const cursor = new Date(start)
  let guard = 0
  while (cursor <= end && guard < maxDays) {
    const pad = (n: number) => String(n).padStart(2, '0')
    const iso = `${cursor.getFullYear()}-${pad(cursor.getMonth() + 1)}-${pad(cursor.getDate())}`
    const point = byDay.get(iso)
    categories.push(cursor.toLocaleDateString('en-GB', { day: '2-digit', month: 'short' }))
    increased.push(point?.increased ?? 0)
    decreased.push(point?.decreased ?? 0)
    cursor.setDate(cursor.getDate() + 1)
    guard += 1
  }
  return {
    categories,
    increased,
    decreased,
    empty: increased.every((n) => n === 0) && decreased.every((n) => n === 0),
    // A range longer than the chart draws is stated, never quietly clipped: a column
    // strip that stops halfway through a quarter reads as a quarter that stopped.
    truncated: cursor <= end,
  }
}

export interface SourceSlice {
  key: string
  label: string
  value: number
  netDelta: number
  revisions: number
  share: number
}

/**
 * Movement by the kind of document that caused it.
 *
 * Sliced on the ABSOLUTE delta: a purchase that added ₹50,000 of cost and a return that took
 * ₹50,000 back are both half the work on this screen, and netting them to zero would draw a
 * source that caused a hundred revisions as no slice at all.
 */
export function sourceSlices(summary: RevisionSummary | null, labelFor: (code: string | null) => string): SourceSlice[] {
  if (!summary) return []
  const total = summary.by_source.reduce((sum, s) => sum + Math.abs(s.abs_delta), 0)
  return summary.by_source
    .filter((s) => s.abs_delta > 0)
    .map((s) => ({
      key: s.document_type ?? 'unknown',
      label: labelFor(s.document_type),
      value: s.abs_delta,
      netDelta: s.net_delta,
      revisions: s.revisions,
      share: total > 0 ? (s.abs_delta / total) * 100 : 0,
    }))
}

export interface AckProgress {
  total: number
  acknowledged: number
  pending: number
  percent: number
  state: 'clear' | 'on-track' | 'attention'
  title: string
  detail: string
}

/** Above this many unacknowledged revisions the card stops congratulating anybody. */
export const PENDING_ATTENTION_THRESHOLD = 10

export function ackProgress(summary: RevisionSummary | null): AckProgress | null {
  if (!summary) return null
  const { revisions, acknowledged, pending } = summary.company
  const percent = revisions > 0 ? Math.round((acknowledged / revisions) * 100) : 100
  if (pending === 0) {
    return {
      total: revisions,
      acknowledged,
      pending,
      percent,
      state: 'clear',
      title: 'All caught up',
      detail: 'Every valuation revision has been acknowledged by Books.',
    }
  }
  if (pending >= PENDING_ATTENTION_THRESHOLD) {
    return {
      total: revisions,
      acknowledged,
      pending,
      percent,
      state: 'attention',
      title: 'Action required',
      detail: 'Unacknowledged revisions keep showing up in reconciliation until Books re-posts the COGS.',
    }
  }
  return {
    total: revisions,
    acknowledged,
    pending,
    percent,
    state: 'on-track',
    title: "You're on track",
    detail: 'Keep acknowledging as Books re-posts, and reconciliation stays clean.',
  }
}

// ---------------------------------------------------------------------------
// Insights
// ---------------------------------------------------------------------------

/**
 * What the engine recorded as the reason it re-costed. These are the only "why" this screen
 * can state, because they are the trigger the job was queued with — not a guess made from
 * the shape of the numbers.
 */
export const TRIGGER_LABELS: Record<string, string> = {
  backdated_document: 'Back-dated document postings',
  reversal: 'Document reversals',
  revaluation: 'Stock revaluations',
  method_change: 'A valuation method change',
  manual: 'Manually queued recalculations',
  migration_rebuild: 'A migration rebuild',
}

export function triggerLabel(kind: string | null | undefined): string {
  if (!kind) return 'Recalculations with no recorded trigger'
  return TRIGGER_LABELS[kind] ?? humanize(kind)
}

/**
 * An item whose rate moved far further this time than it usually does.
 *
 * Deliberately conservative, because an "anomaly" a reader chases and finds nothing behind
 * costs more than one the screen kept quiet about:
 *
 *  - the item needs a real baseline (at least `minSamples` revisions in the window), so a
 *    first-ever revision is never an anomaly;
 *  - the move has to be at least `minChangePct`, so a 0.3% drift against a 0.1% average does
 *    not qualify on the ratio alone;
 *  - and it has to be at least `multiple` times that baseline.
 */
export function findAnomalies(
  summary: RevisionSummary | null,
  { minSamples = 3, minChangePct = 10, multiple = 2 } = {},
): RevisionItemSplit[] {
  if (!summary) return []
  return summary.top_items
    .filter((item) => {
      const peak = item.peak_change_pct
      const baseline = item.baseline_pct
      if (peak === null || baseline === null) return false
      if (item.baseline_samples < minSamples) return false
      if (peak < minChangePct) return false
      return baseline > 0 && peak >= baseline * multiple
    })
    .sort((a, b) => (b.peak_change_pct ?? 0) - (a.peak_change_pct ?? 0))
}

export interface RevisionInsight {
  key: string
  kind: 'driver' | 'anomaly' | 'contributor' | 'backlog'
  /** The claim's strength, shown as the block's eyebrow. */
  label: string
  title: string
  /** In base currency, when the insight is about money. */
  amount?: number
  percent?: number
  detail: string
  tone: Tone
  link?: { to: string; label: string }
}

/**
 * The insight panel's contents.
 *
 * Every line is arithmetic over figures the API returned, and it is worded as what it is: a
 * share, a comparison against a stated baseline, a count of jobs by their recorded trigger.
 * Nothing here says "because" — "Possible contributor" is the strongest claim available,
 * because correlation between a trigger and a delta is all the data supports.
 */
export function buildInsights(summary: RevisionSummary | null): RevisionInsight[] {
  if (!summary) return []
  const out: RevisionInsight[] = []
  const { filtered, top_items: topItems, triggers, company } = summary

  const driver = topItems[0]
  if (driver && driver.abs_delta > 0) {
    const share = filtered.abs_delta > 0 ? (driver.abs_delta / filtered.abs_delta) * 100 : 0
    out.push({
      key: `driver-${driver.item_id}`,
      kind: 'driver',
      label: 'Top variance driver',
      title: driver.item_sku || driver.item_name || `Item #${driver.item_id}`,
      amount: driver.net_delta,
      percent: share,
      detail: `${share.toFixed(0)}% of the valuation movement in view, across ${driver.revisions} revision${driver.revisions === 1 ? '' : 's'}.`,
      tone: driver.net_delta >= 0 ? 'danger' : 'success',
      link: { to: `/valuation/cost-layers?item_id=${driver.item_id}`, label: 'Open cost layers' },
    })
  }

  const anomaly = findAnomalies(summary)[0]
  if (anomaly) {
    out.push({
      key: `anomaly-${anomaly.item_id}`,
      kind: 'anomaly',
      label: 'Unusual rate change',
      title: anomaly.item_sku || anomaly.item_name || `Item #${anomaly.item_id}`,
      percent: anomaly.peak_change_pct ?? undefined,
      detail: `Rate moved ${(anomaly.peak_change_pct ?? 0).toFixed(0)}% against a ${(anomaly.baseline_pct ?? 0).toFixed(1)}% average over the last ${summary.baseline_days} days (${anomaly.baseline_samples} revisions).`,
      tone: 'warning',
      link: { to: `/valuation/cost-layers?item_id=${anomaly.item_id}`, label: 'Investigate cost layers' },
    })
  }

  const trigger = dominantTrigger(triggers, filtered.revisions)
  if (trigger) {
    out.push({
      key: `trigger-${trigger.trigger_kind ?? 'none'}`,
      kind: 'contributor',
      label: 'Possible contributor',
      title: triggerLabel(trigger.trigger_kind),
      detail: `${trigger.jobs} recalculation job${trigger.jobs === 1 ? '' : 's'} with this trigger produced ${trigger.revisions} of the ${filtered.revisions} revisions in view.`,
      tone: 'info',
      link: trigger.trigger_kind
        ? { to: `/valuation/recalculations?trigger_kind=${trigger.trigger_kind}`, label: 'See the jobs' }
        : undefined,
    })
  }

  if (company.pending > 0) {
    out.push({
      key: 'backlog',
      kind: 'backlog',
      label: 'Reconciliation exposure',
      title: `${company.pending} awaiting Books`,
      amount: company.pending_delta,
      detail:
        company.awaiting_publish > 0
          ? `${company.awaiting_publish} of them have not been published to Books yet.`
          : 'All of them are with Books, waiting for the COGS to be re-posted.',
      tone: company.pending >= PENDING_ATTENTION_THRESHOLD ? 'danger' : 'warning',
      link: { to: '/reconciliation/posting-status', label: 'Open reconciliation' },
    })
  }

  return out
}

/** The trigger behind at least half the revisions in view, if there is one. */
export function dominantTrigger(
  triggers: readonly RevisionTriggerSplit[],
  totalRevisions: number,
): RevisionTriggerSplit | null {
  if (totalRevisions <= 0) return null
  const top = [...triggers].sort((a, b) => b.revisions - a.revisions)[0]
  if (!top || top.revisions === 0) return null
  return top.revisions / totalRevisions >= 0.5 ? top : null
}

export interface RevisionAction {
  key: string
  label: string
  to: string
}

/**
 * What to do next — every entry a route that exists, gated by the permission that route needs.
 *
 * An action nobody can perform is worse than no suggestion: it sends an operator to a screen
 * that will refuse them.
 */
export function buildActions(
  summary: RevisionSummary | null,
  can: { recalculate: boolean; reconcile: boolean },
): RevisionAction[] {
  if (!summary) return []
  const out: RevisionAction[] = []
  if (summary.company.pending > 0 && can.reconcile) {
    out.push({
      key: 'reconcile',
      label: `Clear ${summary.company.pending} unacknowledged revision${summary.company.pending === 1 ? '' : 's'} in reconciliation`,
      to: '/reconciliation/posting-status',
    })
  }
  const backdated = summary.triggers.find((t) => t.trigger_kind === 'backdated_document')
  if (backdated && backdated.revisions > 0) {
    out.push({
      key: 'backdated',
      label: `Review the ${backdated.jobs} back-dated recalculation${backdated.jobs === 1 ? '' : 's'}`,
      to: '/valuation/recalculations?trigger_kind=backdated_document',
    })
  }
  if (summary.jobs.failed > 0 && can.recalculate) {
    out.push({
      key: 'failed-jobs',
      label: `Investigate ${summary.jobs.failed} failed recalculation job${summary.jobs.failed === 1 ? '' : 's'}`,
      to: '/valuation/recalculations?status=FAILED',
    })
  }
  const anomaly = findAnomalies(summary)[0]
  if (anomaly) {
    out.push({
      key: `layers-${anomaly.item_id}`,
      label: `Check the cost layers of ${anomaly.item_sku || anomaly.item_name || `item #${anomaly.item_id}`}`,
      to: `/valuation/cost-layers?item_id=${anomaly.item_id}`,
    })
  }
  if (summary.jobs.queued + summary.jobs.running > 0 && can.recalculate) {
    out.push({
      key: 'queue',
      label: `Watch ${summary.jobs.queued + summary.jobs.running} job${summary.jobs.queued + summary.jobs.running === 1 ? '' : 's'} still in the queue`,
      to: '/valuation/recalculations?status=QUEUED,RUNNING',
    })
  }
  return out.slice(0, 4)
}
