import { describe, expect, it } from 'vitest'
import {
  ACCENT_VAR_NAMES,
  DARK_SURFACE,
  deriveAccentVars,
  hexToRgbArr,
  liftForDark,
  relLuminance,
  tripleToArr,
} from './appearance'
import { ERP_THEME_OPTIONS } from '../config/brandColors'

const triple = (s: string) => s.split(' ').map(Number)

describe('hexToRgbArr', () => {
  it('parses a six-digit hex with or without the hash', () => {
    expect(hexToRgbArr('#25B003')).toEqual([37, 176, 3])
    expect(hexToRgbArr('25b003')).toEqual([37, 176, 3])
  })

  it('rejects anything that is not six hex digits', () => {
    expect(hexToRgbArr('#25B0')).toBeNull()
    expect(hexToRgbArr('')).toBeNull()
    expect(hexToRgbArr(null)).toBeNull()
    expect(hexToRgbArr('#zzzzzz')).toBeNull()
  })
})

describe('tripleToArr', () => {
  it('parses a space separated triple', () => {
    expect(tripleToArr('37 176 3')).toEqual([37, 176, 3])
    expect(tripleToArr('  37   176 3 ')).toEqual([37, 176, 3])
  })

  it('rejects the wrong arity or non-numbers', () => {
    expect(tripleToArr('37 176')).toBeNull()
    expect(tripleToArr('37 176 x')).toBeNull()
  })
})

describe('relLuminance', () => {
  it('runs from black to white', () => {
    expect(relLuminance([0, 0, 0])).toBe(0)
    expect(relLuminance([255, 255, 255])).toBeCloseTo(1, 5)
  })
})

describe('liftForDark', () => {
  it('brightens a colour until it clears the contrast floor', () => {
    const lifted = liftForDark([0, 40, 0])
    expect(relLuminance(lifted)).toBeGreaterThanOrEqual(0.18)
  })

  it('leaves a colour that already clears the floor alone', () => {
    const bright: [number, number, number] = [200, 220, 240]
    expect(liftForDark(bright)).toEqual(bright)
  })
})

describe('deriveAccentVars', () => {
  it('returns null for an unparseable colour', () => {
    expect(deriveAccentVars('nope', 'light')).toBeNull()
    expect(deriveAccentVars(null, 'dark')).toBeNull()
  })

  it('writes every accent variable in both modes', () => {
    for (const mode of ['light', 'dark'] as const) {
      const vars = deriveAccentVars('#25B003', mode)
      expect(vars).not.toBeNull()
      for (const name of ACCENT_VAR_NAMES) {
        expect(triple(vars![name])).toHaveLength(3)
      }
    }
  })

  it('keeps the primary as given in light mode and darkens hover then active', () => {
    const vars = deriveAccentVars('#25B003', 'light')!
    expect(vars['--color-primary']).toBe('37 176 3')
    const hover = relLuminance(triple(vars['--color-primary-hover']) as [number, number, number])
    const active = relLuminance(triple(vars['--color-primary-active']) as [number, number, number])
    expect(hover).toBeLessThan(relLuminance([37, 176, 3]))
    expect(active).toBeLessThan(hover)
  })

  it('blends the light tint toward white and the dark tint toward the dark surface', () => {
    const light = triple(deriveAccentVars('#25B003', 'light')!['--color-primary-light'])
    expect(light.every((c) => c > 200)).toBe(true)

    const dark = triple(deriveAccentVars('#25B003', 'dark')!['--color-primary-light'])
    // Within a short distance of --color-surface in the .dark block.
    const distance = Math.hypot(...dark.map((c, i) => c - DARK_SURFACE[i]))
    expect(distance).toBeLessThan(40)
  })

  it('lifts a dark accent for contrast on the dark surface', () => {
    const dark = triple(deriveAccentVars('#0B3D0B', 'dark')!['--color-primary'])
    expect(relLuminance(dark as [number, number, number])).toBeGreaterThanOrEqual(0.18)
  })

  it('honours an explicit secondary colour', () => {
    const vars = deriveAccentVars('#25B003', 'light', '21 128 61')!
    expect(vars['--color-secondary']).toBe('21 128 61')
  })

  it('accepts a triple string and an array as well as hex', () => {
    const fromHex = deriveAccentVars('#25B003', 'light')
    expect(deriveAccentVars('37 176 3', 'light')).toEqual(fromHex)
    expect(deriveAccentVars([37, 176, 3], 'light')).toEqual(fromHex)
  })

  it('clamps every channel into 0-255', () => {
    for (const mode of ['light', 'dark'] as const) {
      for (const name of ACCENT_VAR_NAMES) {
        const value = triple(deriveAccentVars('#FFFFFF', mode)![name])
        expect(value.every((c) => c >= 0 && c <= 255 && Number.isInteger(c))).toBe(true)
      }
    }
  })

  it('reproduces the static preset triples in theme/tokens.css', () => {
    // The `[data-theme]` blocks were generated by this function; if the maths
    // drifts, a preset and the equivalent custom colour stop matching.
    for (const preset of ERP_THEME_OPTIONS) {
      const vars = deriveAccentVars(preset.swatch, 'light')!
      expect(vars['--color-primary']).toBe(preset.primary)
    }
  })
})
